import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const areas = [
  "Administração",
  "Agronomia",
  "Alimentação",
  "Arte",
  "Artes Visuais",
  "Assistência Social",
  "Atendimento",
  "Auditoria",
  "Aviação",
  "Bancos",
  "Beleza",
  "Bem-estar",
  "Biologia",
  "Biomedicina",
  "Biotecnologia",
  "Cinema",
  "Ciência",
  "Ciência da Computação",
  "Ciências Biológicas",
  "Ciências Contábeis",
  "Ciências Econômicas",
  "Comercial",
  "Comércio",
  "Comunicação",
  "Comunicação Social",
  "Compras",
  "Compliance",
  "Construção Civil",
  "Construção e Incorporação",
  "Consultoria",
  "Contabilidade",
  "Criação",
  "Design",
  "Direito",
  "Diplomacia",
  "E-commerce",
  "Economia",
  "Educação",
  "Educação Física",
  "Energias",
  "Engenharia",
  "Engenharia Civil",
  "Engenharia de Produção",
  "Engenharia Elétrica",
  "Engenharia Mecânica",
  "Enfermagem",
  "Entertenimento",
  "Entregas Urbanas",
  "Esportes",
  "Estatística",
  "Estilo",
  "Eventos",
  "Farmácia",
  "Farmacêutica",
  "Filosofia",
  "Física",
  "Fisioterapia",
  "Fiscal",
  "Fitness",
  "Fotografia",
  "Gás",
  "Gastronomia",
  "Games",
  "Gamificação",
  "Geografia",
  "Governamental",
  "História",
  "Hotelaria",
  "Imobiliário",
  "Indústria",
  "Investimentos",
  "ISO",
  "Jornalismo",
  "Jurídico",
  "Laboratórios",
  "Limpeza",
  "Logística",
  "Manutenção",
  "Manutenção Industrial",
  "Manufatura",
  "Marketing",
  "Matemática",
  "Meio Ambiente",
  "Medicina",
  "Medicina Veterinária",
  "Mineração",
  "Moda",
  "Museus e Patrimônio",
  "Negócios",
  "Nutrição",
  "Odontologia",
  "ONGs",
  "Pedagogia",
  "Pesquisa",
  "Planejamento",
  "PMO",
  "Portuário",
  "Produção Audiovisual",
  "Produção Cultural",
  "Propaganda",
  "Projetos Sociais",
  "Psicologia",
  "Publicidade",
  "Qualidade",
  "Química",
  "Recursos Humanos",
  "Relações Internacionais",
  "Relações Públicas",
  "SAC",
  "Saúde",
  "Saneamento",
  "Segurança Patrimonial",
  "Seguros",
  "Serviços Gerais",
  "Setor Público",
  "Siderurgia",
  "Sociologia",
  "Suporte",
  "Suprimentos",
  "Tecnologia da Informação",
  "Telecomunicações",
  "Terceiro Setor",
  "Transportes",
  "Transporte Aéreo",
  "Transporte Ferroviário",
  "Transporte Marítimo",
  "Turismo",
  "Urbanismo",
  "Varejo",
  "Veterinária",
  "Vendas",
  "Vigilância"
];

async function main() {
  console.log('🌱 Iniciando seed de áreas de formação/profissionais...');
  console.log(`Total de áreas únicas: ${areas.length}`);

  for (const nome of areas) {
    await prisma.areaFormacao.upsert({
      where: { nome },
      update: {},
      create: { nome },
    });
  }

  console.log('✅ Áreas inseridas com sucesso!');
}

main()
  .catch((e) => {
    console.error('❌ Erro ao popular áreas:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
